# Generated by Django 4.2.6 on 2023-10-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHotel',
            fields=[
                ('daily_hotel_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('daily_hotel_address', models.CharField(max_length=255)),
                ('daily_hotel_image_link', models.TextField(blank=True, null=True)),
                ('daily_hotel_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('daily_hotel_link', models.TextField(blank=True, null=True)),
                ('daily_hotel_date', models.DateField(blank=True, null=True)),
                ('daily_hotel_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodChoice',
            fields=[
                ('acc_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('acc_address', models.CharField(max_length=255)),
                ('acc_image_link', models.TextField(blank=True, null=True)),
                ('acc_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('acc_link', models.TextField(blank=True, null=True)),
                ('acc_date', models.DateField(blank=True, null=True)),
                ('acc_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goodchoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverBlog',
            fields=[
                ('naver_blog_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('naver_blog_title', models.CharField(max_length=200)),
                ('naver_blog_link', models.TextField(blank=True, null=True)),
                ('naver_blog_image', models.TextField(blank=True, null=True)),
                ('naver_blog_hashtag', models.TextField(blank=True, null=True)),
                ('naver_bloger_name', models.DateField(blank=True, null=True)),
                ('naver_blog_content_likeit_count', models.IntegerField(blank=True, null=True)),
                ('naver_blog_content_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=200)),
                ('place_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant_link', models.TextField(blank=True, null=True)),
                ('restaurant_image', models.TextField(blank=True, null=True)),
                ('restaurant_hashtag', models.TextField(blank=True, null=True)),
                ('restaurant_shop_name', models.TextField(blank=True, null=True)),
                ('restaurant_content_likeit_count', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('restaurant_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('restaurant_review_num_count', models.IntegerField(blank=True, null=True)),
                ('restaurant_avg_price', models.IntegerField(blank=True, null=True)),
                ('restaurant_shop_category', models.TextField(blank=True, null=True)),
                ('restaurant_map_x', models.IntegerField(blank=True, null=True)),
                ('restaurant_map_y', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tripbtoz',
            fields=[
                ('trip_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('trip_address', models.CharField(max_length=255)),
                ('trip_image_link', models.TextField(blank=True, null=True)),
                ('trip_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('trip_link', models.TextField(blank=True, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('trip_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tripbtoz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitkorea',
            fields=[
                ('visitkorea_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('visitkorea_title', models.CharField(blank=True, max_length=255, null=True)),
                ('visitkorea_tel', models.CharField(blank=True, max_length=50, null=True)),
                ('visitkorea_firstimage', models.CharField(blank=True, max_length=255, null=True)),
                ('visitkorea_address', models.CharField(blank=True, max_length=255, null=True)),
                ('visitkorea_mapx', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('visitkorea_mapy', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('visitkorea_mlevel', models.IntegerField(blank=True, null=True)),
                ('visitkorea_overview', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitkorea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yanolja',
            fields=[
                ('yanolja_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('yanolja_address', models.CharField(max_length=255)),
                ('yanolja_image_link', models.TextField(blank=True, null=True)),
                ('yanolja_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('yanolja_link', models.TextField(blank=True, null=True)),
                ('yanolja_date', models.DateField(blank=True, null=True)),
                ('yanolja_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yanolja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('youtube_id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_title', models.CharField(max_length=200)),
                ('youtube_link', models.TextField(blank=True, null=True)),
                ('youtube_image', models.TextField(blank=True, null=True)),
                ('youtube_hashtag', models.TextField(blank=True, null=True)),
                ('youtube_channel_name', models.DateField(blank=True, null=True)),
                ('youtube_channel_count', models.IntegerField(blank=True, null=True)),
                ('youtube_content_like_count', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('youtube_comment_like_count', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('youtube_content_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NearAttraction',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inneats_app.place')),
            ],
            options={
                'db_table': 'near_attraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NearRestaurant',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inneats_app.place')),
            ],
            options={
                'db_table': 'near_restaurant',
                'managed': False,
            },
        ),
    ]
